name: Develop PR

on:
  push:
    branches:
      - develop
#  Currently there is no PR, so runs when push to develop
#  pull_request:
#    types: [opened, synchronize, reopened, ready_for_review]
#    branches:
#      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew allTest
